### ISSUE TITLE
invalid variables

### ISSUE THREAD

**Issue by vkadykova** [szagoruyko/attention-transfer#20]
When I run cifar.py I have the error:
new() received an invalid combination of arguments - got (Tensor, int, int, int), but expected one of:
 * (torch.device device)
 * (tuple of ints size, torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (object data, torch.device device)
What is the problem?
Thanks for the answer!

**Comment by bupt-zsp** [comment]
I meet the same problem, did you solve it now?

**Comment by vkadykova** [comment]
Still no. Write, please, if you solve it:)

**Comment by bupt-zsp** [comment]
It's a version problem, I can run it in pytorch 0.2.0.

**Comment by szagoruyko** [comment]
thats due to torch.IntTensor becoming a variable, so creating a new tensor with shape from torch.IntTensor is not possible without explicit cast to `int` now. going to update the code for PyTorch 0.4 now

**Comment by szagoruyko** [comment]
fixed by #21

**Comment by vkadykova** [comment]
Thanks a lot!
