### ISSUE TITLE
how to resolve this error 

### ISSUE THREAD

**Issue by kanzaali** [szagoruyko/attention-transfer#36]
File "cifar.py", line 126
    o = block(o, params, f'{base}.block{i} ', mode, stride if i == 0 else 1)
                                           ^
SyntaxError: invalid syntax
![error](https://user-images.githubusercontent.com/33715985/52197932-991be300-28a4-11e9-9140-72bad4b0f2f6.png)

**Comment by szagoruyko** [comment]
use python 3.6 or higher
