### ISSUE TITLE
Question on Code

### ISSUE THREAD

**Issue by zhenxing1992** [szagoruyko/attention-transfer#8]
thank you for your code , it's very helpful for me to study computer vision.
but it is shame that i can't run this code correctly,
i think it's maybe the matter of the edition of software
so, there is a issue i want to know that the edition of software, such us python, opencv, 
what i used is python 2.7  pencv 3.2.0

thank you very much

**Comment by szagoruyko** [comment]
what's the error you get? I used python 2.7 and opencv 3.2, right

**Comment by zhenxing1992** [comment]
When I run code 'python cifar.py --save logs/resnet_40_1_teacher --depth 40 --width 1',  there is a error that from torchvision import cvtransforms, that means i can't import name transforms.
 Should I change the import part   'from torchvision import cvtransforms' to  'from torchvision import transforms as cvtransforms'?

**Comment by szagoruyko** [comment]
@zhenxing1992 please follow the installation instructions in README, you need to install torchvision from my fork, it has cvtransforms.

**Comment by zhenxing1992** [comment]
thank you very much .
i will train again immediately.

**Comment by szagoruyko** [comment]
I just merged #9, so that it works with vanilla pytorch and torchvision.

**Comment by zhenxing1992** [comment]
i made it ,  thank you very much.
